In [1]:
a=[1,2,3]
type(a)

list

ARRAY CREATION


In [11]:
import numpy as np
a = np.array([1, 2, 3])             # Create 1D array
b= np.array([[1, 2], [3, 4]])       # Create 2D array
z = np.zeros((2, 3))                # Array of zeros
o = np.ones((3, 3))                 # Array of ones
r = np.arange(0, 10, 2)             # Even numbers 0-8
l = np.linspace(0, 1, 5)            # 5 values between 0–1
type(a)
print(b)
print(z)
print(o)
print(r)
print(l)

[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


ARRAY ATTRIBUTE

In [8]:
print(a.shape)     # Shape (rows, columns)
print(a.ndim)      # Number of dimensions
print(a.dtype)     # Data type of elements



(3,)
1
int64


INDEXING AND SLICING

In [9]:
print(b[0, 1])     # Access element (row 0, col 1)
print(r[1:4])      # Slice from index 1 to 3


2
[2 4 6]


MATHEMATICAL OPERATION

In [11]:
print(a + 5)       # Add scalar
print(a * 2)       # Multiply each element by 2
print(a + b[0,1])    # Element-wise addition (broadcasting)
print(np.dot(b, b))# Matrix multiplication


[6 7 8]
[2 4 6]
[3 4 5]
[[ 7 10]
 [15 22]]


USEFUL FUNCTION

In [12]:
print(np.sum(a))   # Sum of all elements
print(np.mean(a))  # Average
print(np.max(a))   # Maximum value
print(np.sqrt(a))  # Square root of each element


6
2.0
3
[1.         1.41421356 1.73205081]


RESHAPING ARRAY

In [13]:
x = np.arange(6).reshape(2, 3)    # Convert 1D to 2x3 array
print(x.T)                        # Transpose rows and columns



[[0 3]
 [1 4]
 [2 5]]


RANDOM NUMBERS


In [15]:
rand_arr = np.random.rand(2, 3)   # Random floats (0 to 1)
rand_int = np.random.randint(1, 10, 5)  # 5 random ints between 1–9
print(rand_arr)
print(rand_int)


[[0.13083243 0.17707831 0.70754938]
 [0.84110815 0.35438772 0.93940165]]
[7 6 3 8 4]


SAVE AND LOAD ARRAY


In [16]:
np.save('array_file.npy', a)      # Save array
loaded = np.load('array_file.npy')# Load array
print(loaded)



[1 2 3]


LINEAR ALGEBRA

In [17]:
m = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(m))           # Inverse
print(np.linalg.det(m))           # Determinant



[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


LOGICAL AND SORTING

In [18]:
arr = np.array([1, 3, 2, 3])
print(np.unique(arr))             # Unique elements
print(np.sort(arr))               # Sorted array
print(np.where(arr > 2))          # Indices where condition true


[1 2 3]
[1 2 3 3]
(array([1, 3]),)


BASIC NDARRAY

In [2]:
import numpy as np
a= [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])
print(x)


[[ 1  2  3  4]
 [10 20 30 40]]


In [3]:
x=np.array([1,2,4],dtype =np.float32)
print(x)

[1. 2. 4.]


ARRAY OF ONES

In [5]:
np.ones(3,dtype=np.int32)

array([1, 1, 1], dtype=int32)

RONDAM NUMBERS IN NDARRAY

In [6]:
np.random.randint(1,20, size=(3,3))

array([[15, 16,  4],
       [11,  3, 17],
       [ 7, 19,  9]], dtype=int32)

In [7]:
np.random.randn(3,6)

array([[-0.77764733, -1.66752683,  0.75842038, -0.83905226,  0.56881526,
        -0.54271525],
       [-0.56144894, -0.53987287,  1.25768747,  1.02234637,  0.43148812,
         0.65111324],
       [ 1.48293823,  2.50703614, -0.11291717,  0.49595579, -0.27947728,
         1.27854403]])

In [9]:
np.random.choice([2,3,4,7,9])

np.int64(4)

AN ARRAY OF YOUR CHOICE

In [3]:
import numpy as np
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [4]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

IDENTITY MATRIX

In [5]:
x=np.eye(4, k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


EVENLY SPACED NDARRAY

In [6]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [8]:
np.linspace(1,3,6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

SHAPE OF NUMPY ARRAY

In [15]:
a = [10,20,30,40,50]
b=[1,2,3,4,5]
y = np.array([a,b])
print(y)
y.shape ,y.size

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


((2, 5), 10)

RESHAPING OF NUMPY ARRAY

In [ ]:
a=np.array([10,20,30,21])
print(a)
a.reshape(2,2)

[10 20 30 21]


array([[10, 20],
       [30, 21]])

In [26]:
np.reshape(a,(2,2))

array([[10, 20],
       [30, 21]])